<?php

namespace Database\Seeders;

use App\Models\CatalogPreset;
use Illuminate\Database\Seeder;

class CatalogPresetSeeder extends Seeder
{
    public function run(): void
    {
        $presets = [
            // International Cloud/VPS/Hosting
            ['type_slug' => 'cloud', 'name' => 'Amazon Web Services', 'slug' => 'amazonwebservices', 'icon' => 'amazonwebservices', 'icon_set' => 'simple-icons', 'color' => '#FF9900', 'default_url' => 'https://aws.amazon.com', 'aliases' => ['AWS', 'Amazon', 'амазон', 'эймазон'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 1],
            ['type_slug' => 'cloud', 'name' => 'Google Cloud', 'slug' => 'googlecloud', 'icon' => 'googlecloud', 'icon_set' => 'simple-icons', 'color' => '#4285F4', 'default_url' => 'https://cloud.google.com', 'aliases' => ['GCP', 'гугл клауд', 'Google Cloud Platform'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 2],
            ['type_slug' => 'cloud', 'name' => 'Microsoft Azure', 'slug' => 'microsoftazure', 'icon' => 'microsoftazure', 'icon_set' => 'simple-icons', 'color' => '#0078D4', 'default_url' => 'https://portal.azure.com', 'aliases' => ['Azure', 'Азур', 'Microsoft Cloud'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 3],
            ['type_slug' => 'vps', 'name' => 'DigitalOcean', 'slug' => 'digitalocean', 'icon' => 'digitalocean', 'icon_set' => 'simple-icons', 'color' => '#0080FF', 'default_url' => 'https://cloud.digitalocean.com', 'aliases' => ['DO', 'Digital Ocean', 'диджитал оушен', 'droplet', 'дроплет'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 4],
            ['type_slug' => 'vps', 'name' => 'Vultr', 'slug' => 'vultr', 'icon' => 'vultr', 'icon_set' => 'simple-icons', 'color' => '#007BFC', 'default_url' => 'https://my.vultr.com', 'aliases' => ['вултр'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 5],
            ['type_slug' => 'vps', 'name' => 'Linode (Akamai)', 'slug' => 'linode', 'icon' => 'linode', 'icon_set' => 'simple-icons', 'color' => '#00A95C', 'default_url' => 'https://cloud.linode.com', 'aliases' => ['Akamai Cloud', 'линод'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 6],
            ['type_slug' => 'vps', 'name' => 'Hetzner', 'slug' => 'hetzner', 'icon' => 'hetzner', 'icon_set' => 'simple-icons', 'color' => '#D50C2D', 'default_url' => 'https://console.hetzner.cloud', 'aliases' => ['хетцнер', 'hetzner cloud'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 7],
            ['type_slug' => 'vps', 'name' => 'OVHcloud', 'slug' => 'ovh', 'icon' => 'ovh', 'icon_set' => 'simple-icons', 'color' => '#123F6D', 'default_url' => 'https://www.ovh.com', 'aliases' => ['OVH', 'ОВХ'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 8],
            ['type_slug' => 'vps', 'name' => 'Contabo', 'slug' => 'contabo', 'icon' => 'contabo', 'icon_set' => 'custom', 'color' => '#0E5AA7', 'default_url' => 'https://my.contabo.com', 'aliases' => ['контабо'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 9],
            ['type_slug' => 'cloud', 'name' => 'Scaleway', 'slug' => 'scaleway', 'icon' => 'scaleway', 'icon_set' => 'simple-icons', 'color' => '#4F0599', 'default_url' => 'https://console.scaleway.com', 'aliases' => ['скейлвей'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 10],
            ['type_slug' => 'cloud', 'name' => 'Oracle Cloud', 'slug' => 'oracle', 'icon' => 'oracle', 'icon_set' => 'simple-icons', 'color' => '#F80000', 'default_url' => 'https://cloud.oracle.com', 'aliases' => ['OCI', 'Oracle', 'оракл'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 11],
            ['type_slug' => 'cdn', 'name' => 'Cloudflare', 'slug' => 'cloudflare', 'icon' => 'cloudflare', 'icon_set' => 'simple-icons', 'color' => '#F38020', 'default_url' => 'https://dash.cloudflare.com', 'aliases' => ['CF', 'клаудфлер', 'cloudflare CDN'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 12],
            ['type_slug' => 'cdn', 'name' => 'Fastly', 'slug' => 'fastly', 'icon' => 'fastly', 'icon_set' => 'simple-icons', 'color' => '#FF282D', 'default_url' => 'https://manage.fastly.com', 'aliases' => [], 'region' => 'global', 'is_popular' => false, 'sort_order' => 13],
            ['type_slug' => 'hosting', 'name' => 'Heroku', 'slug' => 'heroku', 'icon' => 'heroku', 'icon_set' => 'simple-icons', 'color' => '#430098', 'default_url' => 'https://dashboard.heroku.com', 'aliases' => ['хероку'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 14],
            ['type_slug' => 'hosting', 'name' => 'Vercel', 'slug' => 'vercel', 'icon' => 'vercel', 'icon_set' => 'simple-icons', 'color' => '#000000', 'default_url' => 'https://vercel.com/dashboard', 'aliases' => ['версел', 'Zeit'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 15],
            ['type_slug' => 'hosting', 'name' => 'Netlify', 'slug' => 'netlify', 'icon' => 'netlify', 'icon_set' => 'simple-icons', 'color' => '#00C7B7', 'default_url' => 'https://app.netlify.com', 'aliases' => ['нетлифай'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 16],
            ['type_slug' => 'hosting', 'name' => 'Render', 'slug' => 'render', 'icon' => 'render', 'icon_set' => 'simple-icons', 'color' => '#46E3B7', 'default_url' => 'https://dashboard.render.com', 'aliases' => ['рендер'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 17],
            ['type_slug' => 'hosting', 'name' => 'Railway', 'slug' => 'railway', 'icon' => 'railway', 'icon_set' => 'simple-icons', 'color' => '#0B0D0E', 'default_url' => 'https://railway.app', 'aliases' => [], 'region' => 'global', 'is_popular' => false, 'sort_order' => 18],
            ['type_slug' => 'backup', 'name' => 'Backblaze', 'slug' => 'backblaze', 'icon' => 'backblaze', 'icon_set' => 'simple-icons', 'color' => '#E21E29', 'default_url' => 'https://secure.backblaze.com', 'aliases' => ['B2', 'бэкблейз'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 19],
            // RU hosting/cloud
            ['type_slug' => 'hosting', 'name' => 'Timeweb', 'slug' => 'timeweb', 'icon' => 'timeweb', 'icon_set' => 'custom', 'color' => '#0066FF', 'default_url' => 'https://timeweb.com/ru/my', 'aliases' => ['таймвеб', 'тайм веб', 'timeweb cloud', 'TWC'], 'region' => 'ru', 'is_popular' => true, 'sort_order' => 20],
            ['type_slug' => 'cloud', 'name' => 'Selectel', 'slug' => 'selectel', 'icon' => 'selectel', 'icon_set' => 'custom', 'color' => '#FF4C00', 'default_url' => 'https://my.selectel.ru', 'aliases' => ['селектел'], 'region' => 'ru', 'is_popular' => true, 'sort_order' => 21],
            ['type_slug' => 'cloud', 'name' => 'Yandex Cloud', 'slug' => 'yandexcloud', 'icon' => 'yandexcloud', 'icon_set' => 'custom', 'color' => '#FC3F1D', 'default_url' => 'https://console.cloud.yandex.ru', 'aliases' => ['Яндекс Облако', 'YC', 'яндекс клауд'], 'region' => 'ru', 'is_popular' => true, 'sort_order' => 22],
            ['type_slug' => 'cloud', 'name' => 'VK Cloud', 'slug' => 'vkcloud', 'icon' => 'vk', 'icon_set' => 'simple-icons', 'color' => '#0077FF', 'default_url' => 'https://cloud.vk.com', 'aliases' => ['VK', 'мейлру облако', 'Mail.ru Cloud'], 'region' => 'ru', 'is_popular' => false, 'sort_order' => 23],
            ['type_slug' => 'cloud', 'name' => 'Cloud.ru (SberCloud)', 'slug' => 'cloudru', 'icon' => 'cloudru', 'icon_set' => 'custom', 'color' => '#15D55B', 'default_url' => 'https://cloud.ru', 'aliases' => ['СберКлауд', 'SberCloud'], 'region' => 'ru', 'is_popular' => false, 'sort_order' => 24],
            ['type_slug' => 'hosting', 'name' => 'Beget', 'slug' => 'beget', 'icon' => 'beget', 'icon_set' => 'custom', 'color' => '#1E73BE', 'default_url' => 'https://beget.com/ru', 'aliases' => ['бегет'], 'region' => 'ru', 'is_popular' => true, 'sort_order' => 25],
            ['type_slug' => 'hosting', 'name' => 'REG.RU', 'slug' => 'regru', 'icon' => 'regru', 'icon_set' => 'custom', 'color' => '#1175C8', 'default_url' => 'https://www.reg.ru', 'aliases' => ['рег ру', 'регру'], 'region' => 'ru', 'is_popular' => true, 'sort_order' => 26],
            ['type_slug' => 'domain', 'name' => 'RU-CENTER (nic.ru)', 'slug' => 'nicru', 'icon' => 'nicru', 'icon_set' => 'custom', 'color' => '#E2231A', 'default_url' => 'https://www.nic.ru', 'aliases' => ['nic.ru', 'РУ-ЦЕНТР', 'НИК'], 'region' => 'ru', 'is_popular' => false, 'sort_order' => 27],
            ['type_slug' => 'vps', 'name' => 'VDSina', 'slug' => 'vdsina', 'icon' => 'vdsina', 'icon_set' => 'custom', 'color' => '#2A8FF7', 'default_url' => 'https://vdsina.ru', 'aliases' => ['вдсина', 'вдс'], 'region' => 'ru', 'is_popular' => false, 'sort_order' => 28],
            ['type_slug' => 'vps', 'name' => 'RuVDS', 'slug' => 'ruvds', 'icon' => 'ruvds', 'icon_set' => 'custom', 'color' => '#E30613', 'default_url' => 'https://ruvds.com', 'aliases' => ['рувдс'], 'region' => 'ru', 'is_popular' => false, 'sort_order' => 29],
            ['type_slug' => 'vps', 'name' => 'FirstVDS', 'slug' => 'firstvds', 'icon' => 'firstvds', 'icon_set' => 'custom', 'color' => '#F39200', 'default_url' => 'https://firstvds.ru', 'aliases' => ['фёрствдс', 'firstVDS'], 'region' => 'ru', 'is_popular' => false, 'sort_order' => 30],
            ['type_slug' => 'vps', 'name' => 'Aeza', 'slug' => 'aeza', 'icon' => 'aeza', 'icon_set' => 'custom', 'color' => '#6C5CE7', 'default_url' => 'https://aeza.net', 'aliases' => ['аеза'], 'region' => 'ru', 'is_popular' => false, 'sort_order' => 31],
            ['type_slug' => 'domain', 'name' => '2domains', 'slug' => '2domains', 'icon' => '2domains', 'icon_set' => 'custom', 'color' => '#0099DD', 'default_url' => 'https://2domains.ru', 'aliases' => ['2домейнс', 'два домена'], 'region' => 'ru', 'is_popular' => false, 'sort_order' => 32],
            // Domains/SSL
            ['type_slug' => 'domain', 'name' => 'Namecheap', 'slug' => 'namecheap', 'icon' => 'namecheap', 'icon_set' => 'simple-icons', 'color' => '#DE3723', 'default_url' => 'https://www.namecheap.com', 'aliases' => ['неймчип'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 33],
            ['type_slug' => 'domain', 'name' => 'GoDaddy', 'slug' => 'godaddy', 'icon' => 'godaddy', 'icon_set' => 'simple-icons', 'color' => '#1BDBDB', 'default_url' => 'https://www.godaddy.com', 'aliases' => ['годэдди'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 34],
            ['type_slug' => 'ssl', 'name' => "Let's Encrypt", 'slug' => 'letsencrypt', 'icon' => 'letsencrypt', 'icon_set' => 'simple-icons', 'color' => '#003A70', 'default_url' => 'https://letsencrypt.org', 'aliases' => ['LE', 'lets encrypt', 'летс энкрипт'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 35],
            // Email/Communication
            ['type_slug' => 'email', 'name' => 'Google Workspace', 'slug' => 'googleworkspace', 'icon' => 'google', 'icon_set' => 'simple-icons', 'color' => '#4285F4', 'default_url' => 'https://workspace.google.com', 'aliases' => ['GSuite', 'G Suite', 'гугл воркспейс'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 36],
            ['type_slug' => 'email', 'name' => 'Microsoft 365', 'slug' => 'microsoft365', 'icon' => 'microsoft365', 'icon_set' => 'custom', 'color' => '#D83B01', 'default_url' => 'https://portal.office.com', 'aliases' => ['Office 365', 'M365', 'майкрософт 365'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 37],
            ['type_slug' => 'email', 'name' => 'Proton Mail', 'slug' => 'protonmail', 'icon' => 'protonmail', 'icon_set' => 'simple-icons', 'color' => '#6D4AFF', 'default_url' => 'https://mail.proton.me', 'aliases' => ['ProtonMail', 'протон'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 38],
            ['type_slug' => 'communication', 'name' => 'Slack', 'slug' => 'slack', 'icon' => 'slack', 'icon_set' => 'simple-icons', 'color' => '#4A154B', 'default_url' => 'https://slack.com', 'aliases' => ['слак'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 39],
            ['type_slug' => 'communication', 'name' => 'Discord', 'slug' => 'discord', 'icon' => 'discord', 'icon_set' => 'simple-icons', 'color' => '#5865F2', 'default_url' => 'https://discord.com', 'aliases' => ['дискорд'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 40],
            ['type_slug' => 'communication', 'name' => 'Zoom', 'slug' => 'zoom', 'icon' => 'zoom', 'icon_set' => 'simple-icons', 'color' => '#0B5CFF', 'default_url' => 'https://zoom.us', 'aliases' => ['зум'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 41],
            ['type_slug' => 'communication', 'name' => 'Telegram Premium', 'slug' => 'telegram', 'icon' => 'telegram', 'icon_set' => 'simple-icons', 'color' => '#26A5E4', 'default_url' => 'https://t.me', 'aliases' => ['ТГ', 'телеграм', 'TG Premium'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 42],
            // Dev tools
            ['type_slug' => 'dev_tool', 'name' => 'GitHub', 'slug' => 'github', 'icon' => 'github', 'icon_set' => 'simple-icons', 'color' => '#181717', 'default_url' => 'https://github.com', 'aliases' => ['гитхаб', 'гит хаб'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 43],
            ['type_slug' => 'dev_tool', 'name' => 'GitLab', 'slug' => 'gitlab', 'icon' => 'gitlab', 'icon_set' => 'simple-icons', 'color' => '#FC6D26', 'default_url' => 'https://gitlab.com', 'aliases' => ['гитлаб'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 44],
            ['type_slug' => 'dev_tool', 'name' => 'Bitbucket', 'slug' => 'bitbucket', 'icon' => 'bitbucket', 'icon_set' => 'simple-icons', 'color' => '#0052CC', 'default_url' => 'https://bitbucket.org', 'aliases' => ['битбакет'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 45],
            ['type_slug' => 'dev_tool', 'name' => 'Docker Hub', 'slug' => 'docker', 'icon' => 'docker', 'icon_set' => 'simple-icons', 'color' => '#2496ED', 'default_url' => 'https://hub.docker.com', 'aliases' => ['Docker', 'докер'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 46],
            ['type_slug' => 'license', 'name' => 'JetBrains', 'slug' => 'jetbrains', 'icon' => 'jetbrains', 'icon_set' => 'simple-icons', 'color' => '#000000', 'default_url' => 'https://account.jetbrains.com', 'aliases' => ['джетбрейнс', 'IntelliJ', 'PhpStorm', 'PyCharm'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 47],
            // DBaaS
            ['type_slug' => 'database_service', 'name' => 'MongoDB Atlas', 'slug' => 'mongodb', 'icon' => 'mongodb', 'icon_set' => 'simple-icons', 'color' => '#47A248', 'default_url' => 'https://cloud.mongodb.com', 'aliases' => ['Mongo', 'монго'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 48],
            ['type_slug' => 'database_service', 'name' => 'Supabase', 'slug' => 'supabase', 'icon' => 'supabase', 'icon_set' => 'simple-icons', 'color' => '#3FCF8E', 'default_url' => 'https://app.supabase.com', 'aliases' => ['супабейс'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 49],
            ['type_slug' => 'database_service', 'name' => 'Redis Cloud', 'slug' => 'redis', 'icon' => 'redis', 'icon_set' => 'simple-icons', 'color' => '#FF4438', 'default_url' => 'https://app.redislabs.com', 'aliases' => ['редис'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 50],
            // Monitoring
            ['type_slug' => 'monitoring', 'name' => 'Datadog', 'slug' => 'datadog', 'icon' => 'datadog', 'icon_set' => 'simple-icons', 'color' => '#632CA6', 'default_url' => 'https://app.datadoghq.com', 'aliases' => ['датадог'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 51],
            ['type_slug' => 'monitoring', 'name' => 'Sentry', 'slug' => 'sentry', 'icon' => 'sentry', 'icon_set' => 'simple-icons', 'color' => '#362D59', 'default_url' => 'https://sentry.io', 'aliases' => ['сентри'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 52],
            ['type_slug' => 'monitoring', 'name' => 'Grafana Cloud', 'slug' => 'grafana', 'icon' => 'grafana', 'icon_set' => 'simple-icons', 'color' => '#F46800', 'default_url' => 'https://grafana.com', 'aliases' => ['графана'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 53],
            ['type_slug' => 'monitoring', 'name' => 'UptimeRobot', 'slug' => 'uptimerobot', 'icon' => 'uptimerobot', 'icon_set' => 'simple-icons', 'color' => '#3BD671', 'default_url' => 'https://uptimerobot.com', 'aliases' => ['аптайм робот'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 54],
            // VPN/Security
            ['type_slug' => 'vpn', 'name' => 'NordVPN', 'slug' => 'nordvpn', 'icon' => 'nordvpn', 'icon_set' => 'simple-icons', 'color' => '#4687FF', 'default_url' => 'https://nordvpn.com', 'aliases' => ['норд впн'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 55],
            ['type_slug' => 'vpn', 'name' => 'ExpressVPN', 'slug' => 'expressvpn', 'icon' => 'expressvpn', 'icon_set' => 'simple-icons', 'color' => '#DA3940', 'default_url' => 'https://www.expressvpn.com', 'aliases' => ['экспресс впн'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 56],
            ['type_slug' => 'vpn', 'name' => 'Surfshark', 'slug' => 'surfshark', 'icon' => 'surfshark', 'icon_set' => 'simple-icons', 'color' => '#1EBFBF', 'default_url' => 'https://surfshark.com', 'aliases' => ['серфшарк'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 57],
            ['type_slug' => 'vpn', 'name' => 'Proton VPN', 'slug' => 'protonvpn', 'icon' => 'protonvpn', 'icon_set' => 'simple-icons', 'color' => '#6D4AFF', 'default_url' => 'https://protonvpn.com', 'aliases' => ['протон впн'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 58],
            ['type_slug' => 'security', 'name' => '1Password', 'slug' => '1password', 'icon' => '1password', 'icon_set' => 'simple-icons', 'color' => '#3B66BC', 'default_url' => 'https://1password.com', 'aliases' => ['1пароль', 'один пароль'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 59],
            ['type_slug' => 'security', 'name' => 'Bitwarden', 'slug' => 'bitwarden', 'icon' => 'bitwarden', 'icon_set' => 'simple-icons', 'color' => '#175DDC', 'default_url' => 'https://vault.bitwarden.com', 'aliases' => ['битварден'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 60],
            // Streaming/Media/AI/Games
            ['type_slug' => 'streaming', 'name' => 'Netflix', 'slug' => 'netflix', 'icon' => 'netflix', 'icon_set' => 'simple-icons', 'color' => '#E50914', 'default_url' => 'https://netflix.com', 'aliases' => ['нетфликс'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 61],
            ['type_slug' => 'streaming', 'name' => 'YouTube Premium', 'slug' => 'youtube', 'icon' => 'youtube', 'icon_set' => 'simple-icons', 'color' => '#FF0000', 'default_url' => 'https://youtube.com', 'aliases' => ['ютуб', 'YT Premium'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 62],
            ['type_slug' => 'streaming', 'name' => 'Amazon Prime Video', 'slug' => 'primevideo', 'icon' => 'primevideo', 'icon_set' => 'simple-icons', 'color' => '#00A8E1', 'default_url' => 'https://primevideo.com', 'aliases' => ['Amazon Prime', 'прайм видео'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 63],
            ['type_slug' => 'music', 'name' => 'Spotify', 'slug' => 'spotify', 'icon' => 'spotify', 'icon_set' => 'simple-icons', 'color' => '#1DB954', 'default_url' => 'https://spotify.com', 'aliases' => ['спотифай', 'спотифи'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 64],
            ['type_slug' => 'music', 'name' => 'Apple Music', 'slug' => 'applemusic', 'icon' => 'applemusic', 'icon_set' => 'simple-icons', 'color' => '#FA243C', 'default_url' => 'https://music.apple.com', 'aliases' => ['эппл мьюзик', 'итюнс'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 65],
            ['type_slug' => 'ai', 'name' => 'ChatGPT (OpenAI)', 'slug' => 'openai', 'icon' => 'openai', 'icon_set' => 'simple-icons', 'color' => '#412991', 'default_url' => 'https://chat.openai.com', 'aliases' => ['OpenAI', 'чат гпт', 'гпт', 'GPT', 'ChatGPT', 'openai api'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 66],
            ['type_slug' => 'ai', 'name' => 'Claude (Anthropic)', 'slug' => 'claude', 'icon' => 'claude', 'icon_set' => 'simple-icons', 'color' => '#D97757', 'default_url' => 'https://claude.ai', 'aliases' => ['Anthropic', 'клод', 'клауд', 'claude ai'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 67],
            ['type_slug' => 'ai', 'name' => 'GitHub Copilot', 'slug' => 'githubcopilot', 'icon' => 'github', 'icon_set' => 'simple-icons', 'color' => '#181717', 'default_url' => 'https://github.com/features/copilot', 'aliases' => ['Copilot', 'копилот'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 68],
            ['type_slug' => 'design', 'name' => 'Adobe Creative Cloud', 'slug' => 'adobe', 'icon' => 'adobe', 'icon_set' => 'simple-icons', 'color' => '#FF0000', 'default_url' => 'https://account.adobe.com', 'aliases' => ['Adobe', 'Photoshop', 'Illustrator', 'адоб'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 69],
            ['type_slug' => 'design', 'name' => 'Figma', 'slug' => 'figma', 'icon' => 'figma', 'icon_set' => 'simple-icons', 'color' => '#F24E1E', 'default_url' => 'https://figma.com', 'aliases' => ['фигма'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 70],
            ['type_slug' => 'design', 'name' => 'Canva', 'slug' => 'canva', 'icon' => 'canva', 'icon_set' => 'simple-icons', 'color' => '#00C4CC', 'default_url' => 'https://canva.com', 'aliases' => ['канва'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 71],
            ['type_slug' => 'saas', 'name' => 'Notion', 'slug' => 'notion', 'icon' => 'notion', 'icon_set' => 'simple-icons', 'color' => '#000000', 'default_url' => 'https://notion.so', 'aliases' => ['ноушн', 'нотион'], 'region' => 'global', 'is_popular' => true, 'sort_order' => 72],
            ['type_slug' => 'storage', 'name' => 'Dropbox', 'slug' => 'dropbox', 'icon' => 'dropbox', 'icon_set' => 'simple-icons', 'color' => '#0061FF', 'default_url' => 'https://dropbox.com', 'aliases' => ['дропбокс'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 73],
            ['type_slug' => 'storage', 'name' => 'Google One', 'slug' => 'googleone', 'icon' => 'google', 'icon_set' => 'simple-icons', 'color' => '#4285F4', 'default_url' => 'https://one.google.com', 'aliases' => ['Google Drive', 'гугл диск', 'гугл ван'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 74],
            ['type_slug' => 'storage', 'name' => 'iCloud+', 'slug' => 'icloud', 'icon' => 'icloud', 'icon_set' => 'simple-icons', 'color' => '#3693F3', 'default_url' => 'https://icloud.com', 'aliases' => ['айклауд', 'Apple iCloud'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 75],
            ['type_slug' => 'game', 'name' => 'Steam', 'slug' => 'steam', 'icon' => 'steam', 'icon_set' => 'simple-icons', 'color' => '#000000', 'default_url' => 'https://store.steampowered.com', 'aliases' => ['стим'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 76],
            ['type_slug' => 'game', 'name' => 'PlayStation Plus', 'slug' => 'playstation', 'icon' => 'playstation', 'icon_set' => 'simple-icons', 'color' => '#003791', 'default_url' => 'https://www.playstation.com', 'aliases' => ['PS Plus', 'ПС', 'PlayStation'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 77],
            ['type_slug' => 'game', 'name' => 'Xbox Game Pass', 'slug' => 'xbox', 'icon' => 'xbox', 'icon_set' => 'simple-icons', 'color' => '#107C10', 'default_url' => 'https://www.xbox.com', 'aliases' => ['Иксбокс', 'Game Pass'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 78],
            // RU streaming/media
            ['type_slug' => 'streaming', 'name' => 'Яндекс Плюс', 'slug' => 'yandexplus', 'icon' => 'yandexplus', 'icon_set' => 'custom', 'color' => '#FC3F1D', 'default_url' => 'https://plus.yandex.ru', 'aliases' => ['Yandex Plus', 'Кинопоиск+', 'яндекс плюс'], 'region' => 'ru', 'is_popular' => true, 'sort_order' => 79],
            ['type_slug' => 'streaming', 'name' => 'Кинопоиск', 'slug' => 'kinopoisk', 'icon' => 'kinopoisk', 'icon_set' => 'custom', 'color' => '#FF5500', 'default_url' => 'https://kinopoisk.ru', 'aliases' => ['Kinopoisk', 'кинопоиск'], 'region' => 'ru', 'is_popular' => false, 'sort_order' => 80],
            ['type_slug' => 'streaming', 'name' => 'Okko', 'slug' => 'okko', 'icon' => 'okko', 'icon_set' => 'custom', 'color' => '#5B16D0', 'default_url' => 'https://okko.tv', 'aliases' => ['окко'], 'region' => 'ru', 'is_popular' => false, 'sort_order' => 81],
            ['type_slug' => 'streaming', 'name' => 'IVI', 'slug' => 'ivi', 'icon' => 'ivi', 'icon_set' => 'custom', 'color' => '#ED1C24', 'default_url' => 'https://ivi.ru', 'aliases' => ['иви'], 'region' => 'ru', 'is_popular' => false, 'sort_order' => 82],
            ['type_slug' => 'music', 'name' => 'VK Музыка', 'slug' => 'vkmusic', 'icon' => 'vk', 'icon_set' => 'simple-icons', 'color' => '#0077FF', 'default_url' => 'https://vk.com/music', 'aliases' => ['VK Music', 'ВКонтакте Музыка'], 'region' => 'ru', 'is_popular' => false, 'sort_order' => 83],
            ['type_slug' => 'saas', 'name' => 'Mailchimp', 'slug' => 'mailchimp', 'icon' => 'mailchimp', 'icon_set' => 'simple-icons', 'color' => '#FFE01B', 'default_url' => 'https://mailchimp.com', 'aliases' => ['мейлчимп'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 84],
            ['type_slug' => 'other', 'name' => 'Свой сервис', 'slug' => 'custom-service', 'icon' => 'box', 'icon_set' => 'lucide', 'color' => '#6B7280', 'default_url' => null, 'aliases' => ['custom', 'my service', 'мой сервис', 'другое'], 'region' => 'global', 'is_popular' => false, 'sort_order' => 99],
        ];

        foreach ($presets as $preset) {
            CatalogPreset::updateOrCreate(
                ['slug' => $preset['slug']],
                array_merge($preset, ['aliases' => json_encode($preset['aliases'])])
            );
        }
    }
}
